version: '3.8'

services:
  database-sms:
    container_name: database-sms
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php-sms:
    container_name: php-sms
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/sms-kolodziejski
    depends_on:
      - database-sms
  nginx-sms:
    container_name: nginx-sms
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/sms-kolodziejski
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-sms
      - database-sms
